-- ============================================================
-- V012__seed_fallback_admin.sql
-- Purpose:
--   Safety-net superadmin so the app is reachable on a fresh
--   deploy even when the orchestrator's .env doesn't carry
--   FIRST_ADMIN_EMAIL / FIRST_ADMIN_PASSWORD (in which case the
--   on-startup bootstrap in app.core.bootstrap silently skips and
--   no one can sign in).
--
--   Inserts admin@kpmg.io with the same password used in the dev
--   .env (`345hIk3rw0VwaI2q%*R%`) ONLY if no superadmin exists yet.
--   The Argon2 hash below was generated by app.core.security
--   .hash_password() for that exact plaintext.
--
-- Idempotency: the WHERE NOT EXISTS clause skips the INSERT if any
-- superadmin already exists (regardless of email), so this never
-- conflicts with an admin created by the env-var bootstrap.
--
-- IMPORTANT: rotate this password (Settings -> Password) on first
-- login. The plaintext is documented in the dev .env and is NOT
-- safe for production once anyone but the original developer has
-- repo access.
-- ============================================================

BEGIN;

INSERT INTO users
    (email, full_name, hashed_password, is_active, is_email_verified, is_superadmin)
SELECT
    'admin@kpmg.io',
    'System Administrator',
    '$argon2id$v=19$m=65536,t=3,p=4$U8rZe2+tlbIWQkgphdDamw$kStvs30/+Iq0gqYVa5lMRkmt4tO7LTMea4Hccq02Hvk',
    TRUE,
    TRUE,
    TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE is_superadmin IS TRUE
);

INSERT INTO migrations_history (version, description)
VALUES ('V012', 'users: seed fallback superadmin if none exists')
ON CONFLICT (version) DO NOTHING;

COMMIT;
